### ISSUE TITLE
URL 是单页应用的精华 链接打不开

### ISSUE THREAD

**Issue by liuyu520** [kenberkeley/vue2-scaffold#2]
您好!
[URL 是单页应用的精华](https://kenberkeley.github.io/vue-demo/dist/docs/zh-cn/development/URL-is-soul-of-SPA.html) 的链接打不开
https://kenberkeley.github.io/vue-demo/dist/docs/zh-cn/development/URL-is-soul-of-SPA.html

**Comment by kenberkeley** [comment]
https://kenberkeley.github.io/vue-demo/docs/_book/zh-cn/development/URL-is-soul-of-SPA.html

**Comment by liuyu520** [comment]
谢谢
